# Generated by Django 6.0 on 2026-05-02 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='hearing',
            old_name='hearing_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='hearing',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hearing',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='hearing',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='hearing',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='hearing',
            name='court_name',
            field=models.CharField(default='General Court', max_length=255),
        ),
        migrations.AddField(
            model_name='hearing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hearing',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hearing',
            name='judge_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hearing',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hearing',
            name='title',
            field=models.CharField(default='Hearing', max_length=255),
        ),
    ]
