# Generated by Django 6.0 on 2026-04-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firm',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='firm',
            name='agreement_signed_at',
        ),
        migrations.AlterField(
            model_name='firm',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='firm',
            name='pan_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='firm',
            index=models.Index(fields=['pan_number'], name='firms_firm_pan_num_c0588f_idx'),
        ),
        migrations.AddIndex(
            model_name='firm',
            index=models.Index(fields=['gst_number'], name='firms_firm_gst_num_ee360a_idx'),
        ),
        migrations.AddIndex(
            model_name='firm',
            index=models.Index(fields=['email'], name='firms_firm_email_85bd7f_idx'),
        ),
    ]
