# Generated by Django 6.0 on 2026-05-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0003_firm_website_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='about_text',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='bar_registration',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='font_family',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='practice_areas',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='sidebar_dark',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='theme_color',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='website_email',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='website_enabled',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='website_phone',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='website_template',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='whatsapp_number',
        ),
    ]
