# Generated by Django 6.0 on 2026-05-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0004_remove_firm_about_text_remove_firm_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='about_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='firm',
            name='accent_color',
            field=models.CharField(default='#C9A84C', max_length=20),
        ),
        migrations.AddField(
            model_name='firm',
            name='bar_registration',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='firm',
            name='font_family',
            field=models.CharField(default='DM Sans, sans-serif', max_length=100),
        ),
        migrations.AddField(
            model_name='firm',
            name='gstin',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='firm',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='firm_hero/'),
        ),
        migrations.AddField(
            model_name='firm',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='firm_logos/'),
        ),
        migrations.AddField(
            model_name='firm',
            name='practice_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='firm',
            name='sidebar_dark',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='firm',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='firm',
            name='theme_color',
            field=models.CharField(default='#0D1B2A', max_length=20),
        ),
        migrations.AddField(
            model_name='firm',
            name='website_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='firm',
            name='website_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firm',
            name='website_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='firm',
            name='website_template',
            field=models.CharField(blank=True, default='classic', max_length=30),
        ),
        migrations.AddField(
            model_name='firm',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
