# Generated by Django 6.0 on 2026-05-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0003_firm_branding_fields'),
        ('firms', '0005_firm_about_text_firm_accent_color_and_more'),
    ]

    operations = [
    ]
