# Generated by Django 6.0 on 2026-05-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
    ]
