# Generated by Django 6.0 on 2026-04-30 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('firms', '0002_alter_firm_options_remove_firm_agreement_signed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('invite_type', models.CharField(choices=[('firm', 'Firm'), ('platform', 'Platform')], max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firms.firm')),
            ],
        ),
    ]
