# Generated by Django 6.0 on 2026-05-05 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_invite_role_alter_invite_token_and_more'),
        ('firms', '0002_alter_firm_options_remove_firm_agreement_signed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='role',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='invite',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='firm',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='firms.firm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('lawyer', 'Lawyer'), ('staff', 'Staff')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
