# Generated by Django 6.0 on 2026-05-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_firmsubscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmsubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
