# Generated by Django 6.0 on 2026-05-07 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notification_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_task_assigned', models.BooleanField(default=True)),
                ('email_hearing_reminder', models.BooleanField(default=True)),
                ('email_ticket_update', models.BooleanField(default=True)),
                ('email_payment_receipt', models.BooleanField(default=True)),
                ('email_plan_expiry', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('push_task_assigned', models.BooleanField(default=True)),
                ('push_hearing_reminder', models.BooleanField(default=True)),
                ('push_ticket_update', models.BooleanField(default=True)),
                ('push_case_update', models.BooleanField(default=True)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('whatsapp_task_assigned', models.BooleanField(default=True)),
                ('whatsapp_hearing_reminder', models.BooleanField(default=True)),
                ('whatsapp_payment_receipt', models.BooleanField(default=True)),
                ('whatsapp_ticket_update', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
